"""Enhance profile model with auth and presence fields

Revision ID: bb191415c329
Revises: a3b93044a696
Create Date: 2025-05-25 15:31:52.933564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb191415c329'
down_revision: Union[str, None] = 'a3b93044a696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('profiles', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('profiles', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('preferences', sa.JSON(), nullable=False))
    op.add_column('profiles', sa.Column('privacy_settings', sa.JSON(), nullable=False))
    op.add_column('profiles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('profiles', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('online_status', sa.String(length=20), nullable=False))
    op.add_column('profiles', sa.Column('custom_status_message', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('last_known_location', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('last_location_confidence', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('last_presence_event', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('profiles', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'profiles', ['username'])
    op.create_unique_constraint(None, 'profiles', ['user_id'])
    op.create_unique_constraint(None, 'profiles', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_constraint(None, 'profiles', type_='unique')
    op.alter_column('profiles', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('profiles', 'updated_at')
    op.drop_column('profiles', 'last_presence_event')
    op.drop_column('profiles', 'last_location_confidence')
    op.drop_column('profiles', 'last_known_location')
    op.drop_column('profiles', 'custom_status_message')
    op.drop_column('profiles', 'online_status')
    op.drop_column('profiles', 'last_activity')
    op.drop_column('profiles', 'last_login')
    op.drop_column('profiles', 'is_active')
    op.drop_column('profiles', 'privacy_settings')
    op.drop_column('profiles', 'preferences')
    op.drop_column('profiles', 'avatar_url')
    op.drop_column('profiles', 'phone')
    op.drop_column('profiles', 'website')
    op.drop_column('profiles', 'location')
    op.drop_column('profiles', 'bio')
    op.drop_column('profiles', 'full_name')
    op.drop_column('profiles', 'email')
    op.drop_column('profiles', 'username')
    op.drop_column('profiles', 'user_id')
    # ### end Alembic commands ###
