name: Publish API Docs

on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install project dependencies
        working-directory: ./backend
        run: |
          pip install -r requirements.txt

      - name: Generate OpenAPI JSON
        run: |
          mkdir -p docs/api
          cd backend
          echo 'from main import app; import json; open("../docs/api/openapi.json", "w").write(app.openapi_json())' | python

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/api
