name: Run Tests and Generate API Docs
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest
      
      - name: Debug environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Backend directory contents:"
          ls -la backend/
          echo "Python version:"
          python --version
          echo "Python path:"
          python -c "import sys; print(sys.path)"
          echo "Creating __init__.py files:"
          touch backend/__init__.py
          echo "Backend directory contents after creating __init__.py:"
          ls -la backend/
      
      - name: Try importing backend
        run: |
          echo "Attempting to import backend module..."
          PYTHONPATH=$(pwd) python -c "import backend; print('Backend module imported successfully')"
      
      - name: Generate OpenAPI docs
  run: |
    mkdir -p docs/api
    python scripts/export_openapi.py

        continue-on-error: true
      
      - name: Run tests
        run: |
          PYTHONPATH=$(pwd) pytest
        continue-on-error: true
      
      - name: Upload API docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-docs
          path: docs/api/openapi.json
        if: always()
